# Start from the official PostgreSQL image
FROM postgres:latest

# Set the environment variables for PostgreSQL
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD mypass
ENV POSTGRES_DB django

# Expose the default PostgreSQL port
EXPOSE 5432
