kind: PersistentVolume
apiVersion: v1
metadata:
  name: neo4j-graphs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/Users/collabshare/Projects/collabtest/dbs/neo4j-graphs/db"